=== paissad/waqtsalat-service/src/test/resources/conf/xsd/ws_service_conf_1.0.xsd
<xsd:schema targetNamespace="http://paissad.github.com/waqtsalat-service" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:waqtsalat-service="http://paissad.github.com/waqtsalat-service" elementFormDefault="qualified"
  attributeFormDefault="unqualified" version="1.0">

  <xsd:annotation>
    <xsd:documentation>
      @(#)ws_service_conf_1.0.xsd 1.0 October 22 2011
    </xsd:documentation>
  </xsd:annotation>

  <xsd:annotation>
    <xsd:documentation>
      This file is licensed under GPLv3.
      Author(s): Papa Issa DIAKHATE (paissad@gmail.com)
    </xsd:documentation>
  </xsd:annotation>

  <xsd:annotation>
    <xsd:documentation>
    <![CDATA[
     Waqtsalat-Service configuration file must indicate
     the schema by using the waqtsalat-service namespace:

     http://paissad.github.com/waqtsalat-service

     and indicate the version of the schema by
     using the version element as shown below:

      <waqtsalat-service xmlns="http://paissad.github.com/waqtsalat-service" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:schemaLocation="http://paissad.github.com/waqtsalat-service" 
         version="1.0">
         ...
      </waqtsalat-service>
       ]]>
    </xsd:documentation>
  </xsd:annotation>

  <!-- ******************************************************************** -->

  <xsd:element name="waqtsalat-service">
    <xsd:annotation>
      <xsd:documentation>This tag must be the root element of any XML document.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:all>

        <!-- +++++++++++++++++++++++++++++++++++++++++++ -->

        <xsd:element name="db_conf" minOccurs="1" maxOccurs="1">
          <xsd:annotation>
            <xsd:documentation>This tag and its sub-elements hold the configuration about the database.
            </xsd:documentation>
          </xsd:annotation>
          <xsd:complexType>
            <xsd:all>
              <xsd:element name="db_type" type="waqtsalat-service:db_type_value" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>The type of the database to use for the application (mysql or something else ...)
                  </xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name="db_name" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>The name of the database to use for storing the datas (required)
                  </xsd:documentation>
                </xsd:annotation>
                <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                    <xsd:minLength value="1" />
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="db_host" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>The hostname to use for connecting to the database.</xsd:documentation>
                </xsd:annotation>
                <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                    <xsd:minLength value="1" />
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="db_port" type="waqtsalat-service:port_range" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>The port to use for connecting to the database. The default port is the default one
                    of the
                    chosen type of database. For example, if the chosen type of database if 'mysql', if no port is
                    specified,
                    then the default port of 'msyql' server will be used (usually, for mysql the default port
                    is
                    3306)
                  </xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name="db_user" type="xsd:string" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>The name of the user for connecting to the database.</xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name="db_password" type="xsd:string" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>The password of the user for connecting to the database.</xsd:documentation>
                </xsd:annotation>
              </xsd:element>
            </xsd:all>
          </xsd:complexType>
        </xsd:element>

        <!-- +++++++++++++++++++++++++++++++++++++++++++ -->

        <xsd:element name="properties" minOccurs="0" maxOccurs="1">
          <xsd:annotation>
            <xsd:documentation>A list of name-value pair properties.</xsd:documentation>
          </xsd:annotation>
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="property" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                  <xsd:documentation>A name-value pair.</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:attribute name="name" type="xsd:string" use="required" />
                  <xsd:attribute name="value" type="xsd:string" use="required " />
                  <xsd:attribute name="description" type="xsd:string" use="optional" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>

        <!-- +++++++++++++++++++++++++++++++++++++++++++ -->

      </xsd:all>
      <xsd:attribute name="version" type="waqtsalat-service:versionType" fixed="1.0" use="optional" />
    </xsd:complexType>
  </xsd:element>


  <!-- ******************************************************************** -->

  <xsd:simpleType name="versionType">
    <xsd:restriction base="xsd:token">
      <xsd:pattern value="[0-9]+(\.[0-9]+)*" />
    </xsd:restriction>
  </xsd:simpleType>


  <!-- ******************************************************************** -->

  <xsd:simpleType name="db_type_value">
    <xsd:annotation>
      <xsd:documentation>This type of the database.</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:token">
      <xsd:enumeration value="mysql">
        <xsd:annotation>
          <xsd:documentation>Represents the MYSQL database type.
          </xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
      <xsd:enumeration value="postgresql">
        <xsd:annotation>
          <xsd:documentation>Represents the POSTGRESQL database type.</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
    </xsd:restriction>
  </xsd:simpleType>

  <!-- ******************************************************************** -->

  <xsd:simpleType name="port_range">
    <xsd:annotation>
      <xsd:documentation>Represents the legal port range which is allowed. The range is 1-65535</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:positiveInteger">
      <xsd:minInclusive value="1" fixed="true" />
      <xsd:maxInclusive value="65535" fixed="true" />
    </xsd:restriction>
  </xsd:simpleType>

  <!-- ******************************************************************** -->

</xsd:schema>

=== paissad/waqtsalat-service/waqtsalat-service.xml
<?xml version="1.0" encoding="UTF-8"?>
<waqtsalat-service version="1.0" xmlns="http://paissad.github.com/waqtsalat-service" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://paissad.github.com/waqtsalat-service src/main/webapp/resources/xsd/ws_service_conf_1.0.xsd ">

  <db_conf>
    <db_type>mysql</db_type>
    <db_name>ws_service</db_name>
    <db_host>localhost</db_host>
    <db_port>3306</db_port>
    <db_user>root</db_user>
    <db_password><![CDATA[root]]></db_password>
  </db_conf>

</waqtsalat-service>
